### ISSUE TITLE
package?

### ISSUE THREAD

**Issue by samthomson** [jmathai/php-multi-curl#22]
Hi,

I'd like to use this some more in multiple projects, packaging it up would make that way easier. What do you think?
I'd be happy to make it into a package if you then register it on packagist? Or I could do that too even.

;)

**Comment by jmathai** [comment]
Would appreciate that. There are a few updates I can make to this library as well.

**Comment by samthomson** [comment]
Great. PSR-4 ?

**Comment by jmathai** [comment]
Yeah. PSR-4 :)

**Comment by samthomson** [comment]
Can I do anything extra to get this pull-request through and start using this package? https://github.com/jmathai/php-multi-curl/pull/23

**Comment by jmathai** [comment]
x-posting.

@samthomson Looks like someone has the jmathai/ vendor on packagist for another repository of mine. Any idea how to add this to that or reclaim that vendor prefix?

**Comment by jmathai** [comment]
@samthomson I'm inclined to rev the version of master with the 2.0 (see PR gh-24) version of this library. It's a good time to do it. I've added the tests and configured Travis to run on pushes and pull requests.

https://travis-ci.org/jmathai/php-multi-curl

**Comment by samthomson** [comment]
CI looks good. Not sure about claiming existing vendor name.
I agree, v2, useful to have separation at least until packagist integration is tested.

**Comment by jmathai** [comment]
Merged in gh-23
