### ISSUE TITLE
composer install failed

### ISSUE THREAD

**Issue by linjunjie** [jmathai/php-multi-curl#27]
I git clone to my local directory,and when i run the first command:

    composer install jmathai/php-multi-curl

I got this error:

    Invalid argument jmathai/php-multi-curl. Use "composer require jmathai/php-multi-curl" instead to add packages to your composer.json.

why I got this error ? what's wrong with my composer ? 

and what should I do?

**Comment by jmathai** [comment]
The correct command is `composer require jmathai/php-multi-curl`. I've updated the docs. Thanks.

**Comment by linjunjie** [comment]
But I got a new issue, It's when I run 

`composer require jmathai/php-multi-curl`

I got this:

```
  [InvalidArgumentException]
  Could not find package php-multi-curl at any version for your minimum-stabi
  lity (stable). Check the package spelling or your minimum-stability
```

Is it that I'm in the wrong directory? My directory is in the root directory of the php-multi-curl.
If I run the wrong commd or I make the mistake ,could you correct me with that. 
thand you.
