### ISSUE TITLE
composer install issue

### ISSUE THREAD

**Issue by rtamizh** [jmathai/php-multi-curl#28]
when I run `composer require jmathai/php-multi-curl` i got the following error
```
[InvalidArgumentException]                                                                                                                         
  Could not find package jmathai/php-multi-curl at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

**Comment by vict0ry** [comment]
The same problem :/

**Comment by jmathai** [comment]
Can you try this? `composer require jmathai/php-multi-curl:dev-master -v`

```
➜  test composer require jmathai/php-multi-curl:dev-master -v
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Dependency resolution completed in 0.000 seconds
Analyzed 66 packages to resolve dependencies
Analyzed 64 rules to resolve dependencies
  - Installing jmathai/php-multi-curl (dev-master f62560b)
    Cloning f62560b5ee0ead42bc6b152d4c0969dc8bc496e9

Writing lock file
Generating autoload files
```

**Comment by vict0ry** [comment]
Thank you ! It's working.

**Comment by ousamabenyounes** [comment]
Thank you...
I got the same issue and this also worked fine for me.

**Comment by jmathai** [comment]
Updated the Readme to use this comment for installation until I figure out how to get the old command to work.

**Comment by ousamabenyounes** [comment]
Hi,

I just had the same problem on my own repository.
I fixed it. I created a release with a V0.8 tag.
You can know install my project using classic command:
`composer.phar require ousamabenyounes/log2test
`

So to fix your problem, create a Release, add your comments, and do not forget to tell it is stable release, so do not fill the "This is a pre-release" option.
[ https://help.github.com/articles/working-with-tags/
]( https://help.github.com/articles/working-with-tags/
)
I' ve analyzed your repository, and didn't found any tag / release.

Happy to share this fix with you :)
