### ISSUE TITLE
Parallel task is not executing until I access the response

### ISSUE THREAD

**Issue by MelwinKfr** [jmathai/php-multi-curl#33]
I replaced [this line](https://github.com/jmathai/php-multi-curl/blob/master/src/MultiCurl.php#L84) by `} while ($this->running > 0);` and it works. Because `$this->execStatus` is equal to 0 after curl_multi_exec.

I'm using container `php:7-fpm-alpine` ([Dockerfile](https://github.com/docker-library/php/blob/b208b3bd750feea2c236af0586e544dd1daad8a2/7.0/fpm/alpine/Dockerfile))

Could you help me to understand what's going on ? I don't want to PR bulls**t to you.

**Comment by jmathai** [comment]
Can you render the graph and paste that in? It shows you exactly how the calls are running.

https://github.com/jmathai/php-multi-curl/blob/master/src/example.php#L31

**Comment by MelwinKfr** [comment]
Yep, here it is
```
( ::  code=, start=1480451317.8352, end=, total=)
[====================================================================================================]
```
The same graph is rendered either with my modification or not.

Also, this is the nginx logs without any modification
```
172.17.0.2 - daliminternaltools [29/Nov/2016:20:28:40 +0000] "POST /api/lead-wp-create HTTP/1.1" 200 120 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"
```
and this is the nginx logs with the modification, we can see the two requests.
```
172.17.0.2 - - [29/Nov/2016:20:31:10 +0000] "POST /.parallels/notify?method=NewLead HTTP/1.1" 200 16 "-" "-"
172.17.0.2 - daliminternaltools [29/Nov/2016:20:31:10 +0000] "POST /api/lead-wp-create HTTP/1.1" 200 118 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"
```
Currently i'm just creating a file in the sub request.

**Comment by jmathai** [comment]
Does it look different if you access `code` or `response` before rendering the graph?

If you're not accessing any of the response then there's no guarantee that the calls complete. That's because the calls are made in an asynchronous manner so as to not block the rest of the execution until the response is accessed at which point it would block.

**Comment by MelwinKfr** [comment]
My goal is just to trigger the execution of another script so I can end the parent one and return a response.
```
A ----> | PHP1 | ---> PHP2 (execution could be long)
A <---- |
```
I don't need a guarantee that the second call complete.

Yes it looks totally different, but as far as I understand this, the tasks don't seem to be executed in parallel. For the example I added a 10 seconds sleep in the sub-request and a 5 seconds sleep in the parent request. Here is the output of my script:
```
addCurl duration : 2.5418729782104 s

I sleep 5 seconds.

Accessing the response
Response : Hello world !
Code     : 200
response access duration : 10.12041592598 s

(http://campaign.192.168.1.17.xip.io/.parallels/notify?method=NewLead ::  code=200, start=1480507699.7556, end=1480507717.4221, total=17.665653)
[====================================================================================================]
```
If the tasks had been executed in parallel, accessing the response should have take only about 5 seconds. No ? Here is the output if I remove the 5 seconds sleep in parent request.
```
addCurl duration : 2.5563249588013 s

Accessing the response
Response : Hello world !
Code     : 200
response access duration : 10.109999895096 s

(http://campaign.192.168.1.17.xip.io/.parallels/notify?method=NewLead ::  code=200, start=1480508067.6729, end=1480508080.3392, total=12.666152)
[====================================================================================================]
```
And finally, this is my script:
``` php
        // Notify
        $mc = JMathai\PhpMultiCurl\MultiCurl::getInstance();
        $ch = curl_init($this->getBaseUrl() . '/.parallels/notify?method=NewLead');
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query(array("lead" => json_encode($lead))));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

        $starttime = microtime_float();
        $call = $mc->addCurl($ch);
        echo "\n"."addCurl duration : ".(microtime_float() - $starttime)." s\n\n";

        echo "I sleep 5 seconds.\n\n";
        sleep(5);

        $starttime = microtime_float();
        echo "Accessing the response";
        echo "\nResponse : ".$call->response;
        echo "\nCode     : ".$call->code;
        echo "\n"."response access duration : ".(microtime_float() - $starttime)." s\n\n";

        echo $mc->getSequence()->renderAscii();
```

**Comment by jmathai** [comment]
If you don't want to wait for the request to complete and don't care if it finishes then you're looking for something different than this library. This library lets you make multiple http calls in parallel while you do other stuff but assumes you want to confirm the requests completed.

Here's an example of another library I made that lets you do a "fire and forget" http call.

https://github.com/photo/frontend/blob/master/src/libraries/models/Http.php#L18
