### ISSUE TITLE
curl_multi_select() Bug

### ISSUE THREAD

**Issue by alixaxel** [jmathai/php-multi-curl#9]
Apparently curl_multi_select() started behaving differently and now it results in a infinite loop.

Here are the related PHP bug reports, as well as (at least) 2 solutions:

https://bugs.php.net/bug.php?id=63411
https://bugs.php.net/bug.php?id=63842

**Comment by jmathai** [comment]
Should be fixed here, https://github.com/jmathai/php-multi-curl/blob/master/src/MultiCurl.php#L104

Please reopen if you still see this bug. Note the library has been rev'ed to 2.0 and the older version can be installed via composer with version 1.0.
